---
name: Bug report
description: Integration or entity is not working right
labels: ["bug"]
body:
  - type: input
    attributes:
      label: HA core version
      placeholder: 2023.4.2
  - type: input
    validations:
      required: true
    attributes:
      label: Current integration version
      placeholder: 0.4.3
  - type: input
    validations:
      required: true
    attributes:
      label: Last known working integration version
      placeholder: 0.4.1
  - type: input
    validations:
      required: true
    attributes:
      label: Device type and model
      placeholder: Air Conditioner 22012225
      description: Can be found in Settings -> Devices & Services -> \
        Midea AC LAN -> Devices -> Device Info
  - type: input
    validations:
      required: true
    attributes:
      label: Working mobile app
      placeholder: SmartHome
      description: Which mobile app is used to successfully control the device
  - type: textarea
    validations:
      required: true
    attributes:
      label: The detail description of bug/problem
      description: description the device type and the error details
      value: |
        1. description the device type and name（you may have multiple devices）
        2. description the error action or error info (device have multiple data/features)
  - type: textarea
    attributes:
      label: The logs
      description: DEBUG log MUST be enabled, and execute the action to trigger error log and upload the debug log file as attachment. please refer to README document to enable DEBUG log
      value: |
        1. DEBUG log MUST be enabled (Please refer to README document)
        2. Execute the action to trigger error log（you should description the error action）
        3. Upload the debug log file as attachment。
        4. Please don't paste the log content! upload as a attachment file.
        5. Please don't paste the log content! upload as a attachment file.
        6. Please don't paste the log content! upload as a attachment file.
        ...
