---
name: 新功能请求
description: 请求增加新设备支持或请求为已有设备增加新的功能
labels: ["enhancement"]
body:
  - type: input
    validations:
      required: true
    attributes:
      label: 设备类型及型号 (SN)
      placeholder: Air Conditioner 22012225
      description: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
      value: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
  - type: textarea
    validations:
      required: true
    attributes:
      label: 新功能的具体描述
      value: |
        1. 新增设备支持：希望支持的设备类型以及具体功能，例如查看状态、控制某个功能等
        2. 已有设备新增功能支持：app中可以查看数据，可以控制某个功能，目前不支持，请准确描述
        3. 其他：请准确描述清楚
