---
name: 新功能请求
description: 请求增加新设备支持或请求为已有设备增加新的功能
labels: ["enhancement"]
body:
  - type: input
    validations:
      required: true
    attributes:
      label: 设备类型及设备SN
      placeholder: Air Conditioner 22012225
      description: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
      value: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
        > SN可以通过首页README的debug文档中使用discovery功能获取
  - type: textarea
    validations:
      required: true
    attributes:
      label: 新功能的具体描述
      value: |
        1. 新增设备支持：希望支持的设备类型以及具体功能，例如查看状态、控制某个功能等，务必清晰准确描述。
        2. 已有设备新增功能支持：app中可以查看数据，可以控制某个功能，目前不支持，请清晰准确描述。
        3. 设备SN说明设备详细信息，功能需求必须描述清楚增加什么功能，还需要对应app截图或其它说明，用来证明app确实支持该功能，并且当前app的操作是什么逻辑，执行显示样式和结果
        4. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        5. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        6. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        7. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
        8. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
        9. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
