---
name: 新功能请求
description: 请求增加新设备支持或请求为已有设备增加新的功能
labels: ["enhancement"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 验证issue输入
      description: 在提交之前，请勾选以下选项以证明您已经按模板要求提交了，否则该 issue 将被关闭。
      options:
        - label: 我确认已经完整阅读过 [README文档](https://github.com/wuwentao/midea_ac_lan/blob/master/README_hans.md)，并已掌握如何在HA中使用midea_ac_lan和开启debug log。
          required: false
        - label: 我确认已经阅读过 README中当前issue的[设备使用文档](https://github.com/wuwentao/midea_ac_lan/blob/master/README_hans.md#4-%E5%B7%B2%E6%94%AF%E6%8C%81%E7%9A%84%E8%AE%BE%E5%A4%87) ，但仍无法解决问题
          required: false
        - label: 我已经提交了设备类型和SN信息
          required: true
        - label: 我已经上传了完整的debug log文件，而不是出于对自身的自信而仅提供了部分认为有用的部分。
          required: false
        - label: 我已经准确清晰的描述了当前设备希望增加哪几个功能，对应app的操作截图也已上传
          required: true
        - label: 我是中文用户，使用美的美居，而非海外其他语言用户
          required: false
        - label: 我已在 [Issue Tracker](https://github.com/wuwentao/midea_ac_lan/issues) 中寻找过我要提出的问题，并且没有找到
          required: false
  - type: input
    validations:
      required: true
    attributes:
      label: 设备类型及设备SN
      placeholder: Air Conditioner 22012225
      description: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
      value: |
        > 设备型号可以在 配置 -> 设备与服务 -> Midea AC LAN -> 设备 -> 设备信息 找到
        > SN可以在 配置 -> 设备与服务 -> Midea AC LAN -> 添加设备 -> Just list appliances 找到
        > SN也可以在美居app的设备信息中查看
        > SN可以通过首页README的debug文档中使用discovery功能获取
  - type: textarea
    validations:
      required: true
    attributes:
      label: 新功能的具体描述
      value: |
        1. 新增设备支持：希望支持的设备类型以及具体功能，例如查看状态、控制某个功能等，务必清晰准确描述。
        2. 已有设备新增功能支持：app中可以查看数据，可以控制某个功能，目前不支持，请清晰准确描述。
        3. 设备SN说明设备详细信息，功能需求必须描述清楚增加什么功能，还需要对应app截图或其它说明，用来证明app确实支持该功能，并且当前app的操作是什么逻辑，执行显示样式和结果
        4. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        5. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        6. 已添加成功的设备，新增功能支持，必须上传Debug Log(参考首页README说明)，不按模板提交issue将直接关闭
        7. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
        8. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
        9. 未按模板要求提供信息的issue将直接关闭（如果你有不提交某部分信息的特殊理由，请单独说明）
